### ISSUE TITLE
pip install fails because of missing file

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/deltacd#2]
I was following the directions to do an install as per the README. 

```
(deltacd) nsandhu@BDOMO-DT264615:~/delta/deltacd$ pip install -e .
Obtaining file:///home/nsandhu/delta/deltacd
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/nsandhu/delta/deltacd/setup.py", line 2, in <module>
          import versioneer
      ModuleNotFoundError: No module named 'versioneer'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dwr-psandhu** [comment]
```
pip install versioneer
pip install -e .
```
Seems to work
